<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员信息"
            }

            ,{
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图信息"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"成绩管理",
                        "menuJump":"列表",
                        "tableName":"chengji"
                    }
                ],
                "menu":"成绩管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"成绩类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryChengji"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"分班类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryFenban"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"公告类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryGonggao"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"实训方向类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryShixun"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"实训方向管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryYonghu"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"打卡状态管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryYonghuKaoqinList"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"作业类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryZuoye"
                    }
                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"分班管理",
                        "menuJump":"列表",
                        "tableName":"fenban"
                    }
                ],
                "menu":"分班管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告管理",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"任课老师管理",
                        "menuJump":"列表",
                        "tableName":"laoshi"
                    }
                ],
                "menu":"任课老师管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"实训方向管理",
                        "menuJump":"列表",
                        "tableName":"shixun"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"实训方向报名管理",
                        "menuJump":"列表",
                        "tableName":"shixunOrder"
                    }
                ],
                "menu":"实训方向管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"用户管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"用户管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "打卡",
                            "删除"
                        ],
                        "menu":"学生考勤管理",
                        "menuJump":"列表",
                        "tableName":"yonghuKaoqin"
                    }
                    ,
                    {
                        "buttons":[
                            "订单",
                            "查看",
                            "删除"
                        ],
                        "menu":"学生考勤详情管理",
                        "menuJump":"列表",
                        "tableName":"yonghuKaoqinList"
                    }
                ],
                "menu":"学生考勤管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"作业管理",
                        "menuJump":"列表",
                        "tableName":"zuoye"
                    }
                ],
                "menu":"作业管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除",
                            "审核"
                        ],
                        "menu":"作业提交管理",
                        "menuJump":"列表",
                        "tableName":"zuoyeTijiao"
                    }
                ],
                "menu":"作业提交管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    },
    {
        "backMenu":[
         {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"成绩管理",
                        "menuJump":"列表",
                        "tableName":"chengji"
                    }
                ],
                "menu":"成绩管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                        ],
                        "menu":"分班管理",
                        "menuJump":"列表",
                        "tableName":"fenban"
                    }
                ],
                "menu":"分班管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                        ],
                        "menu":"公告管理",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                        ],
                        "menu":"实训方向管理",
                        "menuJump":"列表",
                        "tableName":"shixun"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                        ],
                        "menu":"实训方向报名管理",
                        "menuJump":"列表",
                        "tableName":"shixunOrder"
                    }
                ],
                "menu":"实训方向管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "打卡",
                            "删除"
                        ],
                        "menu":"学生考勤管理",
                        "menuJump":"列表",
                        "tableName":"yonghuKaoqin"
                    }
                    ,
                    {
                        "buttons":[
                            "订单",
                            "查看",
                            "删除"
                        ],
                        "menu":"学生考勤详情管理",
                        "menuJump":"列表",
                        "tableName":"yonghuKaoqinList"
                    }
                ],
                "menu":"学生考勤管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"作业管理",
                        "menuJump":"列表",
                        "tableName":"zuoye"
                    }
                ],
                "menu":"作业管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除",
                            "审核"
                        ],
                        "menu":"作业提交管理",
                        "menuJump":"列表",
                        "tableName":"zuoyeTijiao"
                    }
                ],
                "menu":"作业提交管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"任课老师",
        "tableName":"laoshi"
    }
];

var hasMessage = '';
